WebApp-OpenIDConnect-DotNet/Controllers/CalendarController.cs
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.OpenIdConnect;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebApp_OpenIDConnect_DotNet.App_Start;
using WebApp_OpenIDConnect_DotNet.Utils;

namespace WebApp_OpenIDConnect_DotNet.Controllers
{
    public class CalendarController : Controller
    {
        public static string[] ReadScope = new[] { "https://outlook.office.com/calendars.read" };
        public static string[] WriteScope = new[] { "https://outlook.office.com/calendars.readwrite" };

        // GET: Calendar
        public async Task<ActionResult> Index(string authError)
        {
            if (!Request.IsAuthenticated)
            {
                // Specify the scopes we need to satisfy in the challenge, space-separated.
                Dictionary<string, string> scopeDict = new Dictionary<string, string>() { { ConvergenceOIDCHandler.ScopeKey, ReadScope[0] } };
                HttpContext.GetOwinContext().Authentication.Challenge(new AuthenticationProperties(scopeDict) { RedirectUri = "/Calendar" }, OpenIdConnectAuthenticationDefaults.AuthenticationType);
                return new HttpUnauthorizedResult();
            }


            // TODO - Get Tokens, Call O365
            AuthenticationResult result = null;

            try
            {
                // Get an access_token
                string userObjectID = ClaimsPrincipal.Current.FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").Value;
                string tenantID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;
                string authority = String.Format(CultureInfo.InvariantCulture, Startup.aadInstance, tenantID);
                AuthenticationContext authContext = new AuthenticationContext(authority, new NaiveSessionCache(userObjectID));
                ClientCredential credential = new ClientCredential(Startup.clientId, Startup.clientSecret);
                result = await authContext.AcquireTokenSilentAsync(ReadScope, credential, UserIdentifier.AnyUser);

                // Read the user's calendar for this week
                HttpClient client = new HttpClient();
                HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, "https://outlook.office.com/api/v1.0/me/calendarview?startDateTime=2015-07-26T01:00:00Z&endDateTime=2015-08-01T23:00:00Z");
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", result.Token);
                HttpResponseMessage response = await client.SendAsync(request);

                if (response.IsSuccessStatusCode)
                {
                    ViewBag.AuthError = true;
                    if (string.IsNullOrEmpty(authError))
                    {
                        ViewBag.AuthError = false;
                    }
                    String responseString = await response.Content.ReadAsStringAsync();
                    JObject mailResponse = JObject.Parse(responseString);
                    JArray messages = mailResponse["value"] as JArray;
                    ViewBag.Events = messages;
                    return View();
                }

                return new RedirectResult("/Error?message=An Error Occurred Reading Mail: " + response.StatusCode);
            }
            catch (AdalException ee)
            {
                return new RedirectResult("/GetConsent?write=false");
            }
            catch (Exception ex)
            {
                return new RedirectResult("/Error?message=An Error Occurred Reading Mail: " + ex.Message);
            }

        }







        // TODO - Challenge for more consent!
        [Authorize]
        public void GetConsent(bool write)
        {
            // Specify the scopes we need to satisfy in the challenge, space-separated.
            string scopes = ReadScope[0];
            if (write)
            {
                scopes += " " + WriteScope[0];
            }
            Dictionary<string, string> scopeDict = new Dictionary<string, string>() { { ConvergenceOIDCHandler.ScopeKey, scopes } };
            HttpContext.GetOwinContext().Authentication.Challenge(new AuthenticationProperties(scopeDict) { RedirectUri = "/Calendar" }, OpenIdConnectAuthenticationDefaults.AuthenticationType);
        }





        // TODO - The same token acquisition & O365 Call
        [Authorize]
        public async Task<ActionResult> AddEvent(string Day, string Time, string Title)
        {
            AuthenticationResult result = null;

            try
            {
                // Get an access_token
                string userObjectID = ClaimsPrincipal.Current.FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").Value;
                string tenantID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;
                string authority = String.Format(CultureInfo.InvariantCulture, Startup.aadInstance, tenantID);
                AuthenticationContext authContext = new AuthenticationContext(authority, new NaiveSessionCache(userObjectID));
                ClientCredential credential = new ClientCredential(Startup.clientId, Startup.clientSecret);
                result = await authContext.AcquireTokenSilentAsync(WriteScope, credential, UserIdentifier.AnyUser);

                // Create POST Data
                int time = Int32.Parse(Time);
                string json = new JavaScriptSerializer().Serialize(new
                {
                    Subject = Title,
                    Start = Day + "T" + time.ToString() + ":00:00Z",
                    End = Day + "T" + (time + 1).ToString() + ":00:00Z"
                });
                
                HttpClient client = new HttpClient();
                HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, "https://outlook.office.com/api/v1.0/me/events");
                request.Content = new StringContent(json, Encoding.UTF8, "application/json");
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", result.Token);
                HttpResponseMessage response = await client.SendAsync(request);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }

                if (response.StatusCode == HttpStatusCode.Unauthorized)
                { 
                    return Redirect("/Calendar/Index?authError=true");
                }

                return new RedirectResult("/Error?message=An Error Occurred Reading Mail: " + response.StatusCode);
            }
            catch (AdalException ee) 
            {
               return Redirect("/Calendar/Index?authError=true");
            }
            catch (Exception ex)
            {
                return new RedirectResult("/Error?message=An Error Occurred Reading Mail: " + ex.Message);
            }
        }
    }
}

WebApp-OpenIDConnect-DotNet/Views/Calendar/Index.cshtml
@{
    ViewBag.Title = "Mail";
}

<h2>Office 365 Calendar API</h2>

<form action="/Calendar/AddEvent" method="post">
    
    <h4>Add a 1-Hour Event This Week:</h4>

    @Html.DropDownList("Day", new List<SelectListItem> {
       new SelectListItem  { Text = "Sunday", Value = "2015-07-26" },
       new SelectListItem  { Text = "Monday", Value = "2015-07-27" },
       new SelectListItem  { Text = "Tuesday", Value = "2015-07-28" },
       new SelectListItem  { Text = "Wednesday", Value = "2015-07-29" },
       new SelectListItem  { Text = "Thursday", Value = "2015-07-30" },
       new SelectListItem  { Text = "Friday", Value = "2015-07-31" },
       new SelectListItem  { Text = "Saturday", Value = "2015-08-01" },
    }, "Select a Day...", null)

    @Html.DropDownList("Time", new List<SelectListItem> {
       new SelectListItem  { Text = "9 AM", Value = "16" },
       new SelectListItem  { Text = "10 AM", Value = "17" },
       new SelectListItem  { Text = "11 AM", Value = "18" },
       new SelectListItem  { Text = "12 PM", Value = "19" },
       new SelectListItem  { Text = "1 PM", Value = "20" },
       new SelectListItem  { Text = "2 PM", Value = "21" },
       new SelectListItem  { Text = "3 PM", Value = "22" },
    }, "Select a Time...", null)

    @Html.TextBox("Title", "")

    <input type="submit" value="Add" />

</form>

@if (ViewBag.AuthError == true)
{
    <p style="color:red">You need to grant permission for us to write to your calendar first.  @Html.ActionLink("Click here.", "GetConsent", "Calendar", new { write = true }, null)</p>
}
else 
{
    <br />
}

<table class="table table-striped table-bordered table-condensed table-hover">
    <tr>
        <th class="claim-type claim-data claim-head">From</th>
        <th class="claim-data claim-head">Subject</th>
        <th class="claim-data claim-head">Day</th>
        <th class="claim-data claim-head">Start</th>
        <th class="claim-data claim-head">End</th>
    </tr>

    @foreach (Newtonsoft.Json.Linq.JObject item in ViewBag.Events)
    {
        var startString = (string)item["Start"];
        var endString = (string)item["End"];
        var startDate = startString.Substring(0, 10);
        var endDate = endString.Substring(0, 10);
        var startTime = (Int32.Parse(startString.Substring(11, 2))-7).ToString() + startString.Substring(13, 3);
        var endTime = (Int32.Parse(endString.Substring(11, 2))-7).ToString() + endString.Substring(13, 3);
    
        <tr>
            <td class="claim-type claim-data">@((string)item["Organizer"]["EmailAddress"]["Address"])</td>
            <td class="claim-data">@((string)item["Subject"])</td>
            <td class="claim-data">@(startDate)</td>
            <td class="claim-data">@(startTime)</td>
            <td class="claim-data">@(endTime)</td>
        </tr>
    }
</table>